freebsd_instance:
  image_family: freebsd-14-0

task:
  name: cargo test (stable)
  env:
    HOME: /tmp # cargo needs it
  install_script: pkg install -y rust
  lockfile_script: cargo generate-lockfile
  cargo_version: cargo version
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build
  test_script: cargo test
  before_cache_script: rm -rf $HOME/.cargo/registry/index
