task:
  name: FreeBSD Test
  freebsd_instance:
    image_family: freebsd-14-2
  env:
    HOME: /tmp
  install_script: 
    - pkg install -y curl
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
  lockfile_script: 
    - source $HOME/.cargo/env
    - cargo generate-lockfile
  cargo_version: 
    - source $HOME/.cargo/env
    - cargo version
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock
  build_script: 
    - source $HOME/.cargo/env
    - cargo build
  test_script: 
    - source $HOME/.cargo/env
    - cargo test
  before_cache_script: rm -rf $HOME/.cargo/registry/index

task:
  name: macos Test
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  env:
    HOME: /tmp
  install_script: 
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
  lockfile_script: 
    - source $HOME/.cargo/env
    - cargo generate-lockfile
  cargo_version: 
    - source $HOME/.cargo/env
    - cargo version
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock
  build_script: 
    - source $HOME/.cargo/env
    - cargo build
  test_script: 
    - source $HOME/.cargo/env
    - cargo test
  before_cache_script: rm -rf $HOME/.cargo/registry/index  
