task:
  name: FreeBSD Test
  freebsd_instance:
    image_family: freebsd-14-0
  env:
    HOME: /tmp
  install_script: pkg install -y rust
  lockfile_script: cargo generate-lockfile
  cargo_version: cargo version
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build
  test_script: cargo test
  before_cache_script: rm -rf $HOME/.cargo/registry/index

task:
  name: macos Test
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  env:
    HOME: /tmp
  install_script: brew install rust
  lockfile_script: cargo generate-lockfile
  cargo_version: cargo version
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build
  test_script: cargo test
  before_cache_script: rm -rf $HOME/.cargo/registry/index  
